import { NextResponse } from 'next/server';

export async function GET() {
  const projects = [
    {
      title: 'Ecommerce',
      isTutorial: false,
      description: `A fullstack eCommerce platform with user authentication, product management, shopping cart, and Mercado Pago payment integration. \nBuilt with Next.js, Supabase, Prisma, Docker, and deployed on Vercel.`,
      link2: 'https://github.com/Fransei29/sport-ecommerce/blob/main/README.md',
      link3: 'https://sport-ecommerce-58pi.vercel.app/',
      previewImage: '/img/ecommerce.jpg',
      logs: [
        'git init',
        'git clone https://github.com/Fransei29/Ecommerce-Tutorial.git',
        'cd Ecommerce-Tutorial',
        'npm install',
        'npm run dev'
      ]
    },    
    {
      title: 'Task Manager',
      isTutorial: false,
      description: `An efficient app for managing tasks with functionalities like creating, editing, deleting, and user authentication. \nIts user-friendly interface supports seamless task and session handling. \nBuilt using React, Next.js, Axios, and PostgreSQL.`,
      link2: 'https://github.com/Fransei29/task-manager.git',
      link3: 'https://task-manager-b-git-main-francos-projects-94304a5e.vercel.app/',
      previewImage: '/img/task.png',
      logs: [
        'git init',
        'git clone https://github.com/Fransei29/task-manager.git',
        'cd task-manager',
        'npm install',
        'README file for environment variables configuration.',
        'npm run dev',
      ],
    },
    {
      title: 'Vestiré',
      isTutorial: false,
      description: `E-commerce platform offering a wide selection of clothing with intuitive navigation and a seamless checkout process. \nI designed and developed the complete user flow, from start to finalizing purchases. \nBuilt using Express, React, Axios, and PostgreSQL.`,
      link2: 'https://github.com/Fransei29/vestire_front.git',
      link3: 'https://vestire-front-s196.vercel.app/',
      previewImage: '/img/vesti.jpg',
      logs: [
        'git init',
        'git clone https://github.com/Fransei29/vestire_front.git',
        'cd vestire_front',
        'npm install',
        'npm run start',
      ],
    },
    {
      title: 'Flipper',
      isTutorial: false,
      description: `A Twitter-inspired app supporting functionalities like tweeting, following, and live updates. \nReal-time interactions are powered by WebSockets, ensuring responsiveness and high user engagement. \nBuilt with Redis, Node.js, Express, Redis, and Tailwind CSS.`,
      link2: 'https://github.com/Fransei29/clonetwitter.git',
      link3: 'https://clonetwitter-zy47-git-main-francos-projects-94304a5e.vercel.app/',
      previewImage: '/img/flipper.png',
      logs: [
        'git init',
        'git clone https://github.com/Fransei29/clonetwitter.git',
        'cd clonetwitter',
        'npm install',
        'npm run start',
      ],
    },
    {
      title: 'Dynamic Blog',
      isTutorial: false,
      description: `A responsive blog application that fetches posts from an RSS feed (TechCrunch) and user-generated content from Airtable. \nFeatures include dynamic routing, user blog management, and a clean, responsive design. \nBuilt using Next.js, Tailwind CSS, and Parser.`,
      link2: 'https://github.com/Fransei29/next-blogs-post/blob/main/app/page.js',
      link3: 'https://next-blogs-post-ahua.vercel.app/',
      previewImage: '/img/next.png',
      logs: [
        'git init',
        'git clone https://github.com/Fransei29/next-blogs-post.git',
        'cd next-blogs-post',
        'npm install',
        'npm run dev',
      ],
    },
    {
      title: 'Trip Planner',
      isTutorial: false,
      description: `Application designed to simplify trip planning with itinerary management and other travel tools. \nIts effective navigation and smooth design enhance the user experience significantly. \nBuilt with Express, React, Axios, and MongoDB.`,
      link2: 'https://github.com/Fransei29/tripplanner.git',
      link3: 'https://trip-planner-c.vercel.app/',
      previewImage: '/img/trip.png',
      logs: [
        'git init',
        'git clone https://github.com/Fransei29/tripplanner.git',
        'cd tripplanner',
        'npm install',
        'npm run start',
      ],
    },
    {
      title: 'Holistic Portal',
      isTutorial: false,
      description: `Informative website showcasing alternative therapies, offering descriptions, client testimonials, and booking options. \nIt focuses on user interaction and professional presentation. \nBuilt using HTML, CSS, and Sass.`,
      link2: 'https://github.com/Fransei29/AmnerisWeb.git',
      link3: 'https://amneris-web.vercel.app/',
      previewImage: '/img/holis.png',
      logs: [
        'git init',
        'git clone https://github.com/Fransei29/AmnerisWeb.git',
        'cd AmnerisWeb',
        'npm install',
        'npm run start',
      ],
    },
    {
      title: "First Portfolio",
      isTutorial: false,
      description: `A polished portfolio website that highlights my initial projects, skills, and design style. \nI carefully crafted the structure and aesthetics, ensuring it was visually attractive and simple to navigate for any visitor. \nBuilt using HTML and CSS.`,
      link2: 'https://github.com/Fransei29/Portfolio.git',
      link3: 'https://portfolio-gamma-green-78.vercel.app/',
      previewImage: '/img/port.png',
      logs: [
        'git init',
        'git clone https://github.com/Fransei29/Portfolio.git',
        'cd Portfolio',
        'go live',
      ],
    },
    {
      title: "Content Management",
      isTutorial: false,
      description: `A robust website for creating, managing, and displaying posts with various content types. \nIt provides tools for users to efficiently handle and organize their digital content. \nBuilt using Express, Sequelize, PostgreSQL, and GraphQL.`,
      link2: 'https://github.com/Fransei29/graphql_front.git',
      previewImage: '/img/gra.png',
      logs: [
        'git init',
        'git clone https://github.com/Fransei29/graphql_front.git',
        'cd graphql_front',
        'npm install',
        'npm run start',
      ],
    },
    {
      title: 'Greengrocery',
      isTutorial: false,
      description: `Online store specializing in fresh groceries with a shopping cart and an optimized shopping experience. \nIt incorporates testing with Jest, ensuring smooth functionality and higher conversion rates for users. \nBuilt using React.`,
      link2: 'https://github.com/Fransei29/Verdufront.git',
      link3: 'https://verdufront-zbzb.vercel.app/',
      previewImage: '/img/verdu.png',
      logs: [
        'git init',
        'git clone https://github.com/Fransei29/Verdufront.git',
        'cd Verdufront',
        'npm install',
        'npm run start',
      ],
    },
  ];

  return NextResponse.json(projects);
}
